#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("MaydSchedulerApp.Resource", IsApplication=true)]

namespace MaydSchedulerApp
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010002
			public const int circleCrop = 2130771970;
			
			// aapt resource value: 0x7f010001
			public const int imageAspectRatio = 2130771969;
			
			// aapt resource value: 0x7f010000
			public const int imageAspectRatioAdjust = 2130771968;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ButtonBlueStyle = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ButtonSignUp = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int edit_text_style = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int global_bg = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Icon = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int profile = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int splash = 2130837510;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070030
			public const int EmpMgmtList = 2131165232;
			
			// aapt resource value: 0x7f07003b
			public const int aboutBtn = 2131165243;
			
			// aapt resource value: 0x7f07003f
			public const int action_button1 = 2131165247;
			
			// aapt resource value: 0x7f070040
			public const int action_button2 = 2131165248;
			
			// aapt resource value: 0x7f070000
			public const int adjust_height = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int adjust_width = 2131165185;
			
			// aapt resource value: 0x7f07002e
			public const int btnAvailCancel = 2131165230;
			
			// aapt resource value: 0x7f07002f
			public const int btnAvailSubmit = 2131165231;
			
			// aapt resource value: 0x7f070012
			public const int btnEditCancel = 2131165202;
			
			// aapt resource value: 0x7f070013
			public const int btnEditSubmit = 2131165203;
			
			// aapt resource value: 0x7f070003
			public const int btnEditTitle = 2131165187;
			
			// aapt resource value: 0x7f07005c
			public const int btnSettingsCancel = 2131165276;
			
			// aapt resource value: 0x7f07005d
			public const int btnSettingsSubmit = 2131165277;
			
			// aapt resource value: 0x7f07006d
			public const int btnStaffingSubmit = 2131165293;
			
			// aapt resource value: 0x7f07005e
			public const int btnStaffingTitle = 2131165278;
			
			// aapt resource value: 0x7f07005b
			public const int btnWeeklySubmit = 2131165275;
			
			// aapt resource value: 0x7f070029
			public const int chkAvailFriday = 2131165225;
			
			// aapt resource value: 0x7f07001d
			public const int chkAvailMonday = 2131165213;
			
			// aapt resource value: 0x7f07002c
			public const int chkAvailSaturday = 2131165228;
			
			// aapt resource value: 0x7f070019
			public const int chkAvailSunday = 2131165209;
			
			// aapt resource value: 0x7f070026
			public const int chkAvailThursday = 2131165222;
			
			// aapt resource value: 0x7f070020
			public const int chkAvailTuesday = 2131165216;
			
			// aapt resource value: 0x7f070023
			public const int chkAvailWednesday = 2131165219;
			
			// aapt resource value: 0x7f070081
			public const int chkFriday = 2131165313;
			
			// aapt resource value: 0x7f070075
			public const int chkMonday = 2131165301;
			
			// aapt resource value: 0x7f070084
			public const int chkSaturday = 2131165316;
			
			// aapt resource value: 0x7f070071
			public const int chkSunday = 2131165297;
			
			// aapt resource value: 0x7f07007e
			public const int chkThursday = 2131165310;
			
			// aapt resource value: 0x7f070078
			public const int chkTuesday = 2131165304;
			
			// aapt resource value: 0x7f07007b
			public const int chkWednesday = 2131165307;
			
			// aapt resource value: 0x7f070041
			public const int chooseWeekListView = 2131165249;
			
			// aapt resource value: 0x7f07000f
			public const int editInputSFriClose = 2131165199;
			
			// aapt resource value: 0x7f07000e
			public const int editInputSFriOpen = 2131165198;
			
			// aapt resource value: 0x7f070007
			public const int editInputSMonClose = 2131165191;
			
			// aapt resource value: 0x7f070006
			public const int editInputSMonOpen = 2131165190;
			
			// aapt resource value: 0x7f070011
			public const int editInputSSatClose = 2131165201;
			
			// aapt resource value: 0x7f070010
			public const int editInputSSatOpen = 2131165200;
			
			// aapt resource value: 0x7f070004
			public const int editInputSSunClose = 2131165188;
			
			// aapt resource value: 0x7f070005
			public const int editInputSSunOpen = 2131165189;
			
			// aapt resource value: 0x7f07000d
			public const int editInputSThuClose = 2131165197;
			
			// aapt resource value: 0x7f07000c
			public const int editInputSThuOpen = 2131165196;
			
			// aapt resource value: 0x7f070009
			public const int editInputSTueClose = 2131165193;
			
			// aapt resource value: 0x7f070008
			public const int editInputSTueOpen = 2131165192;
			
			// aapt resource value: 0x7f07000b
			public const int editInputSWedClose = 2131165195;
			
			// aapt resource value: 0x7f07000a
			public const int editInputSWedOpen = 2131165194;
			
			// aapt resource value: 0x7f07003a
			public const int empMgmtBtn = 2131165242;
			
			// aapt resource value: 0x7f070016
			public const int empPageFirstName = 2131165206;
			
			// aapt resource value: 0x7f070018
			public const int empPageID = 2131165208;
			
			// aapt resource value: 0x7f070015
			public const int empPageLastName = 2131165205;
			
			// aapt resource value: 0x7f070017
			public const int empPagePosition = 2131165207;
			
			// aapt resource value: 0x7f070039
			public const int historyBtn = 2131165241;
			
			// aapt resource value: 0x7f070044
			public const int historyListView = 2131165252;
			
			// aapt resource value: 0x7f070036
			public const int homeRecentWeeks = 2131165238;
			
			// aapt resource value: 0x7f07002a
			public const int inputAvailFriClose = 2131165226;
			
			// aapt resource value: 0x7f070028
			public const int inputAvailFriOpen = 2131165224;
			
			// aapt resource value: 0x7f07001e
			public const int inputAvailMonClose = 2131165214;
			
			// aapt resource value: 0x7f07001c
			public const int inputAvailMonOpen = 2131165212;
			
			// aapt resource value: 0x7f07002d
			public const int inputAvailSatClose = 2131165229;
			
			// aapt resource value: 0x7f07002b
			public const int inputAvailSatOpen = 2131165227;
			
			// aapt resource value: 0x7f07001a
			public const int inputAvailSunClose = 2131165210;
			
			// aapt resource value: 0x7f07001b
			public const int inputAvailSunOpen = 2131165211;
			
			// aapt resource value: 0x7f070027
			public const int inputAvailThuClose = 2131165223;
			
			// aapt resource value: 0x7f070025
			public const int inputAvailThuOpen = 2131165221;
			
			// aapt resource value: 0x7f070021
			public const int inputAvailTueClose = 2131165217;
			
			// aapt resource value: 0x7f07001f
			public const int inputAvailTueOpen = 2131165215;
			
			// aapt resource value: 0x7f070024
			public const int inputAvailWedClose = 2131165220;
			
			// aapt resource value: 0x7f070022
			public const int inputAvailWedOpen = 2131165218;
			
			// aapt resource value: 0x7f07005a
			public const int inputDefaultClose = 2131165274;
			
			// aapt resource value: 0x7f070058
			public const int inputDefaultOpen = 2131165272;
			
			// aapt resource value: 0x7f070050
			public const int inputDefaultShift = 2131165264;
			
			// aapt resource value: 0x7f070082
			public const int inputFriClose = 2131165314;
			
			// aapt resource value: 0x7f070080
			public const int inputFriOpen = 2131165312;
			
			// aapt resource value: 0x7f070054
			public const int inputMaxShift = 2131165268;
			
			// aapt resource value: 0x7f070052
			public const int inputMinShift = 2131165266;
			
			// aapt resource value: 0x7f070076
			public const int inputMonClose = 2131165302;
			
			// aapt resource value: 0x7f070074
			public const int inputMonOpen = 2131165300;
			
			// aapt resource value: 0x7f07006a
			public const int inputSFriClose = 2131165290;
			
			// aapt resource value: 0x7f070069
			public const int inputSFriOpen = 2131165289;
			
			// aapt resource value: 0x7f070062
			public const int inputSMonClose = 2131165282;
			
			// aapt resource value: 0x7f070061
			public const int inputSMonOpen = 2131165281;
			
			// aapt resource value: 0x7f07006c
			public const int inputSSatClose = 2131165292;
			
			// aapt resource value: 0x7f07006b
			public const int inputSSatOpen = 2131165291;
			
			// aapt resource value: 0x7f07005f
			public const int inputSSunClose = 2131165279;
			
			// aapt resource value: 0x7f070060
			public const int inputSSunOpen = 2131165280;
			
			// aapt resource value: 0x7f070068
			public const int inputSThuClose = 2131165288;
			
			// aapt resource value: 0x7f070067
			public const int inputSThuOpen = 2131165287;
			
			// aapt resource value: 0x7f070064
			public const int inputSTueClose = 2131165284;
			
			// aapt resource value: 0x7f070063
			public const int inputSTueOpen = 2131165283;
			
			// aapt resource value: 0x7f070066
			public const int inputSWedClose = 2131165286;
			
			// aapt resource value: 0x7f070065
			public const int inputSWedOpen = 2131165285;
			
			// aapt resource value: 0x7f070085
			public const int inputSatClose = 2131165317;
			
			// aapt resource value: 0x7f070083
			public const int inputSatOpen = 2131165315;
			
			// aapt resource value: 0x7f070056
			public const int inputSkillCap = 2131165270;
			
			// aapt resource value: 0x7f070072
			public const int inputSunClose = 2131165298;
			
			// aapt resource value: 0x7f070073
			public const int inputSunOpen = 2131165299;
			
			// aapt resource value: 0x7f07007f
			public const int inputThuClose = 2131165311;
			
			// aapt resource value: 0x7f07007d
			public const int inputThuOpen = 2131165309;
			
			// aapt resource value: 0x7f070079
			public const int inputTueClose = 2131165305;
			
			// aapt resource value: 0x7f070077
			public const int inputTueOpen = 2131165303;
			
			// aapt resource value: 0x7f07007c
			public const int inputWedClose = 2131165308;
			
			// aapt resource value: 0x7f07007a
			public const int inputWedOpen = 2131165306;
			
			// aapt resource value: 0x7f07003e
			public const int myListView = 2131165246;
			
			// aapt resource value: 0x7f070037
			public const int newWeekBtn = 2131165239;
			
			// aapt resource value: 0x7f070002
			public const int none = 2131165186;
			
			// aapt resource value: 0x7f070042
			public const int pop_button1 = 2131165250;
			
			// aapt resource value: 0x7f070043
			public const int pop_button2 = 2131165251;
			
			// aapt resource value: 0x7f070038
			public const int quickWeekBtn = 2131165240;
			
			// aapt resource value: 0x7f07004e
			public const int scheduleListView = 2131165262;
			
			// aapt resource value: 0x7f07003c
			public const int settingsBtn = 2131165244;
			
			// aapt resource value: 0x7f07006e
			public const int testing_button1 = 2131165294;
			
			// aapt resource value: 0x7f07006f
			public const int testing_button2 = 2131165295;
			
			// aapt resource value: 0x7f070059
			public const int textDefaultClose = 2131165273;
			
			// aapt resource value: 0x7f070057
			public const int textDefaultOpen = 2131165271;
			
			// aapt resource value: 0x7f07004f
			public const int textDefaultShift = 2131165263;
			
			// aapt resource value: 0x7f070053
			public const int textMaxShift = 2131165267;
			
			// aapt resource value: 0x7f070051
			public const int textMinShift = 2131165265;
			
			// aapt resource value: 0x7f070055
			public const int textSkillCap = 2131165269;
			
			// aapt resource value: 0x7f070070
			public const int toolbar = 2131165296;
			
			// aapt resource value: 0x7f07003d
			public const int txtCreateAccount = 2131165245;
			
			// aapt resource value: 0x7f070034
			public const int txtEID = 2131165236;
			
			// aapt resource value: 0x7f070032
			public const int txtFirst = 2131165234;
			
			// aapt resource value: 0x7f07004c
			public const int txtFri = 2131165260;
			
			// aapt resource value: 0x7f070031
			public const int txtLast = 2131165233;
			
			// aapt resource value: 0x7f070048
			public const int txtMon = 2131165256;
			
			// aapt resource value: 0x7f070035
			public const int txtPartFullTime = 2131165237;
			
			// aapt resource value: 0x7f070033
			public const int txtPosition = 2131165235;
			
			// aapt resource value: 0x7f07004d
			public const int txtSat = 2131165261;
			
			// aapt resource value: 0x7f070045
			public const int txtScheduleName = 2131165253;
			
			// aapt resource value: 0x7f070046
			public const int txtSchedulePosition = 2131165254;
			
			// aapt resource value: 0x7f070047
			public const int txtSun = 2131165255;
			
			// aapt resource value: 0x7f07004b
			public const int txtThu = 2131165259;
			
			// aapt resource value: 0x7f070049
			public const int txtTue = 2131165257;
			
			// aapt resource value: 0x7f07004a
			public const int txtWed = 2131165258;
			
			// aapt resource value: 0x7f070014
			public const int weeklyConfigLayout = 2131165204;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f040000
			public const int google_play_services_version = 2130968576;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int AboutPage = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int EditShift = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int EmployeeView = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int EmpMgmtLayout = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int EmpMgmtListView = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Main = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int NewWeek = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int options_menu = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int PickWeekLayout = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int popup_menu = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int ScheduleHistory = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int ScheduleListView = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int ScheduleView = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int SetHours = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int settings = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int Splash = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int StaffingNeeds = 2130903056;
			
			// aapt resource value: 0x7f030011
			public const int testing_menu = 2130903057;
			
			// aapt resource value: 0x7f030012
			public const int ToolBar = 2130903058;
			
			// aapt resource value: 0x7f030013
			public const int WeeklyConfig = 2130903059;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050002
			public const int ApplicationName = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int Hello = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int common_google_play_services_unknown_issue = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int Theme_Splash = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] LoadingImageView = new int[] {
					2130771968,
					2130771969,
					2130771970};
			
			// aapt resource value: 2
			public const int LoadingImageView_circleCrop = 2;
			
			// aapt resource value: 1
			public const int LoadingImageView_imageAspectRatio = 1;
			
			// aapt resource value: 0
			public const int LoadingImageView_imageAspectRatioAdjust = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
