#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("MaydSchedulerApp.Resource", IsApplication=true)]

namespace MaydSchedulerApp
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ButtonBlueStyle = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ButtonSignUp = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int edit_text_style = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int global_bg = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Icon = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int profile = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int splash = 2130837510;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f06002c
			public const int EmpMgmtList = 2131099692;
			
			// aapt resource value: 0x7f060039
			public const int action_button1 = 2131099705;
			
			// aapt resource value: 0x7f06003a
			public const int action_button2 = 2131099706;
			
			// aapt resource value: 0x7f06002a
			public const int btnAvailCancel = 2131099690;
			
			// aapt resource value: 0x7f06002b
			public const int btnAvailSubmit = 2131099691;
			
			// aapt resource value: 0x7f06000f
			public const int btnEditCancel = 2131099663;
			
			// aapt resource value: 0x7f060010
			public const int btnEditSubmit = 2131099664;
			
			// aapt resource value: 0x7f060000
			public const int btnEditTitle = 2131099648;
			
			// aapt resource value: 0x7f060056
			public const int btnSettingsCancel = 2131099734;
			
			// aapt resource value: 0x7f060057
			public const int btnSettingsSubmit = 2131099735;
			
			// aapt resource value: 0x7f060067
			public const int btnStaffingSubmit = 2131099751;
			
			// aapt resource value: 0x7f060058
			public const int btnStaffingTitle = 2131099736;
			
			// aapt resource value: 0x7f060055
			public const int btnWeeklySubmit = 2131099733;
			
			// aapt resource value: 0x7f060025
			public const int chkAvailFriday = 2131099685;
			
			// aapt resource value: 0x7f060019
			public const int chkAvailMonday = 2131099673;
			
			// aapt resource value: 0x7f060028
			public const int chkAvailSaturday = 2131099688;
			
			// aapt resource value: 0x7f060015
			public const int chkAvailSunday = 2131099669;
			
			// aapt resource value: 0x7f060022
			public const int chkAvailThursday = 2131099682;
			
			// aapt resource value: 0x7f06001c
			public const int chkAvailTuesday = 2131099676;
			
			// aapt resource value: 0x7f06001f
			public const int chkAvailWednesday = 2131099679;
			
			// aapt resource value: 0x7f06007b
			public const int chkFriday = 2131099771;
			
			// aapt resource value: 0x7f06006f
			public const int chkMonday = 2131099759;
			
			// aapt resource value: 0x7f06007e
			public const int chkSaturday = 2131099774;
			
			// aapt resource value: 0x7f06006b
			public const int chkSunday = 2131099755;
			
			// aapt resource value: 0x7f060078
			public const int chkThursday = 2131099768;
			
			// aapt resource value: 0x7f060072
			public const int chkTuesday = 2131099762;
			
			// aapt resource value: 0x7f060075
			public const int chkWednesday = 2131099765;
			
			// aapt resource value: 0x7f06003b
			public const int chooseWeekListView = 2131099707;
			
			// aapt resource value: 0x7f06000c
			public const int editInputSFriClose = 2131099660;
			
			// aapt resource value: 0x7f06000b
			public const int editInputSFriOpen = 2131099659;
			
			// aapt resource value: 0x7f060004
			public const int editInputSMonClose = 2131099652;
			
			// aapt resource value: 0x7f060003
			public const int editInputSMonOpen = 2131099651;
			
			// aapt resource value: 0x7f06000e
			public const int editInputSSatClose = 2131099662;
			
			// aapt resource value: 0x7f06000d
			public const int editInputSSatOpen = 2131099661;
			
			// aapt resource value: 0x7f060001
			public const int editInputSSunClose = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int editInputSSunOpen = 2131099650;
			
			// aapt resource value: 0x7f06000a
			public const int editInputSThuClose = 2131099658;
			
			// aapt resource value: 0x7f060009
			public const int editInputSThuOpen = 2131099657;
			
			// aapt resource value: 0x7f060006
			public const int editInputSTueClose = 2131099654;
			
			// aapt resource value: 0x7f060005
			public const int editInputSTueOpen = 2131099653;
			
			// aapt resource value: 0x7f060008
			public const int editInputSWedClose = 2131099656;
			
			// aapt resource value: 0x7f060007
			public const int editInputSWedOpen = 2131099655;
			
			// aapt resource value: 0x7f060033
			public const int editWeekBtn = 2131099699;
			
			// aapt resource value: 0x7f060035
			public const int empMgmtBtn = 2131099701;
			
			// aapt resource value: 0x7f060014
			public const int empPageID = 2131099668;
			
			// aapt resource value: 0x7f060012
			public const int empPageName = 2131099666;
			
			// aapt resource value: 0x7f060013
			public const int empPagePosition = 2131099667;
			
			// aapt resource value: 0x7f060034
			public const int historyBtn = 2131099700;
			
			// aapt resource value: 0x7f06003e
			public const int historyListView = 2131099710;
			
			// aapt resource value: 0x7f060026
			public const int inputAvailFriClose = 2131099686;
			
			// aapt resource value: 0x7f060024
			public const int inputAvailFriOpen = 2131099684;
			
			// aapt resource value: 0x7f06001a
			public const int inputAvailMonClose = 2131099674;
			
			// aapt resource value: 0x7f060018
			public const int inputAvailMonOpen = 2131099672;
			
			// aapt resource value: 0x7f060029
			public const int inputAvailSatClose = 2131099689;
			
			// aapt resource value: 0x7f060027
			public const int inputAvailSatOpen = 2131099687;
			
			// aapt resource value: 0x7f060016
			public const int inputAvailSunClose = 2131099670;
			
			// aapt resource value: 0x7f060017
			public const int inputAvailSunOpen = 2131099671;
			
			// aapt resource value: 0x7f060023
			public const int inputAvailThuClose = 2131099683;
			
			// aapt resource value: 0x7f060021
			public const int inputAvailThuOpen = 2131099681;
			
			// aapt resource value: 0x7f06001d
			public const int inputAvailTueClose = 2131099677;
			
			// aapt resource value: 0x7f06001b
			public const int inputAvailTueOpen = 2131099675;
			
			// aapt resource value: 0x7f060020
			public const int inputAvailWedClose = 2131099680;
			
			// aapt resource value: 0x7f06001e
			public const int inputAvailWedOpen = 2131099678;
			
			// aapt resource value: 0x7f060054
			public const int inputDefaultClose = 2131099732;
			
			// aapt resource value: 0x7f060052
			public const int inputDefaultOpen = 2131099730;
			
			// aapt resource value: 0x7f06004a
			public const int inputDefaultShift = 2131099722;
			
			// aapt resource value: 0x7f06007c
			public const int inputFriClose = 2131099772;
			
			// aapt resource value: 0x7f06007a
			public const int inputFriOpen = 2131099770;
			
			// aapt resource value: 0x7f06004e
			public const int inputMaxShift = 2131099726;
			
			// aapt resource value: 0x7f06004c
			public const int inputMinShift = 2131099724;
			
			// aapt resource value: 0x7f060070
			public const int inputMonClose = 2131099760;
			
			// aapt resource value: 0x7f06006e
			public const int inputMonOpen = 2131099758;
			
			// aapt resource value: 0x7f060064
			public const int inputSFriClose = 2131099748;
			
			// aapt resource value: 0x7f060063
			public const int inputSFriOpen = 2131099747;
			
			// aapt resource value: 0x7f06005c
			public const int inputSMonClose = 2131099740;
			
			// aapt resource value: 0x7f06005b
			public const int inputSMonOpen = 2131099739;
			
			// aapt resource value: 0x7f060066
			public const int inputSSatClose = 2131099750;
			
			// aapt resource value: 0x7f060065
			public const int inputSSatOpen = 2131099749;
			
			// aapt resource value: 0x7f060059
			public const int inputSSunClose = 2131099737;
			
			// aapt resource value: 0x7f06005a
			public const int inputSSunOpen = 2131099738;
			
			// aapt resource value: 0x7f060062
			public const int inputSThuClose = 2131099746;
			
			// aapt resource value: 0x7f060061
			public const int inputSThuOpen = 2131099745;
			
			// aapt resource value: 0x7f06005e
			public const int inputSTueClose = 2131099742;
			
			// aapt resource value: 0x7f06005d
			public const int inputSTueOpen = 2131099741;
			
			// aapt resource value: 0x7f060060
			public const int inputSWedClose = 2131099744;
			
			// aapt resource value: 0x7f06005f
			public const int inputSWedOpen = 2131099743;
			
			// aapt resource value: 0x7f06007f
			public const int inputSatClose = 2131099775;
			
			// aapt resource value: 0x7f06007d
			public const int inputSatOpen = 2131099773;
			
			// aapt resource value: 0x7f060050
			public const int inputSkillCap = 2131099728;
			
			// aapt resource value: 0x7f06006c
			public const int inputSunClose = 2131099756;
			
			// aapt resource value: 0x7f06006d
			public const int inputSunOpen = 2131099757;
			
			// aapt resource value: 0x7f060079
			public const int inputThuClose = 2131099769;
			
			// aapt resource value: 0x7f060077
			public const int inputThuOpen = 2131099767;
			
			// aapt resource value: 0x7f060073
			public const int inputTueClose = 2131099763;
			
			// aapt resource value: 0x7f060071
			public const int inputTueOpen = 2131099761;
			
			// aapt resource value: 0x7f060076
			public const int inputWedClose = 2131099766;
			
			// aapt resource value: 0x7f060074
			public const int inputWedOpen = 2131099764;
			
			// aapt resource value: 0x7f060038
			public const int myListView = 2131099704;
			
			// aapt resource value: 0x7f060032
			public const int newWeekBtn = 2131099698;
			
			// aapt resource value: 0x7f06003c
			public const int pop_button1 = 2131099708;
			
			// aapt resource value: 0x7f06003d
			public const int pop_button2 = 2131099709;
			
			// aapt resource value: 0x7f060048
			public const int scheduleListView = 2131099720;
			
			// aapt resource value: 0x7f060036
			public const int settingsBtn = 2131099702;
			
			// aapt resource value: 0x7f060068
			public const int testing_button1 = 2131099752;
			
			// aapt resource value: 0x7f060069
			public const int testing_button2 = 2131099753;
			
			// aapt resource value: 0x7f060053
			public const int textDefaultClose = 2131099731;
			
			// aapt resource value: 0x7f060051
			public const int textDefaultOpen = 2131099729;
			
			// aapt resource value: 0x7f060049
			public const int textDefaultShift = 2131099721;
			
			// aapt resource value: 0x7f06004d
			public const int textMaxShift = 2131099725;
			
			// aapt resource value: 0x7f06004b
			public const int textMinShift = 2131099723;
			
			// aapt resource value: 0x7f06004f
			public const int textSkillCap = 2131099727;
			
			// aapt resource value: 0x7f06006a
			public const int toolbar = 2131099754;
			
			// aapt resource value: 0x7f060037
			public const int txtCreateAccount = 2131099703;
			
			// aapt resource value: 0x7f060030
			public const int txtEID = 2131099696;
			
			// aapt resource value: 0x7f06002e
			public const int txtFirst = 2131099694;
			
			// aapt resource value: 0x7f060046
			public const int txtFri = 2131099718;
			
			// aapt resource value: 0x7f06002d
			public const int txtLast = 2131099693;
			
			// aapt resource value: 0x7f060042
			public const int txtMon = 2131099714;
			
			// aapt resource value: 0x7f060031
			public const int txtPartFullTime = 2131099697;
			
			// aapt resource value: 0x7f06002f
			public const int txtPosition = 2131099695;
			
			// aapt resource value: 0x7f060047
			public const int txtSat = 2131099719;
			
			// aapt resource value: 0x7f06003f
			public const int txtScheduleName = 2131099711;
			
			// aapt resource value: 0x7f060040
			public const int txtSchedulePosition = 2131099712;
			
			// aapt resource value: 0x7f060041
			public const int txtSun = 2131099713;
			
			// aapt resource value: 0x7f060045
			public const int txtThu = 2131099717;
			
			// aapt resource value: 0x7f060043
			public const int txtTue = 2131099715;
			
			// aapt resource value: 0x7f060044
			public const int txtWed = 2131099716;
			
			// aapt resource value: 0x7f060011
			public const int weeklyConfigLayout = 2131099665;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int EditShift = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int EmployeeView = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int EmpMgmtLayout = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int EmpMgmtListView = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Main = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int NewWeek = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int options_menu = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int PickWeekLayout = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int popup_menu = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int ScheduleHistory = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int ScheduleListView = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int ScheduleView = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int SetHours = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int settings = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int Splash = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int StaffingNeeds = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int testing_menu = 2130903056;
			
			// aapt resource value: 0x7f030011
			public const int ToolBar = 2130903057;
			
			// aapt resource value: 0x7f030012
			public const int WeeklyConfig = 2130903058;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int Theme_Splash = 2131034112;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
