#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("MaydSchedulerApp.Resource", IsApplication=true)]

namespace MaydSchedulerApp
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010002
			public const int circleCrop = 2130771970;
			
			// aapt resource value: 0x7f010001
			public const int imageAspectRatio = 2130771969;
			
			// aapt resource value: 0x7f010000
			public const int imageAspectRatioAdjust = 2130771968;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ButtonBlueStyle = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ButtonSignUp = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int edit_text_style = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int global_bg = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Icon = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int profile = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int splash = 2130837510;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f08003f
			public const int EmpMgmtList = 2131230783;
			
			// aapt resource value: 0x7f08004a
			public const int aboutBtn = 2131230794;
			
			// aapt resource value: 0x7f08004e
			public const int action_button1 = 2131230798;
			
			// aapt resource value: 0x7f080000
			public const int adjust_height = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int adjust_width = 2131230721;
			
			// aapt resource value: 0x7f080004
			public const int availChangeListView = 2131230724;
			
			// aapt resource value: 0x7f08003d
			public const int btnAvailCancel = 2131230781;
			
			// aapt resource value: 0x7f080005
			public const int btnAvailChangeCancel = 2131230725;
			
			// aapt resource value: 0x7f080006
			public const int btnAvailChangeSubmit = 2131230726;
			
			// aapt resource value: 0x7f08003e
			public const int btnAvailSubmit = 2131230782;
			
			// aapt resource value: 0x7f080016
			public const int btnEditCancel = 2131230742;
			
			// aapt resource value: 0x7f080017
			public const int btnEditSubmit = 2131230743;
			
			// aapt resource value: 0x7f080007
			public const int btnEditTitle = 2131230727;
			
			// aapt resource value: 0x7f080054
			public const int btnPosFragCancel = 2131230804;
			
			// aapt resource value: 0x7f080055
			public const int btnPosFragSubmit = 2131230805;
			
			// aapt resource value: 0x7f080058
			public const int btnPosMgrAdd = 2131230808;
			
			// aapt resource value: 0x7f080057
			public const int btnPosMgrCancel = 2131230807;
			
			// aapt resource value: 0x7f08006d
			public const int btnPositionEdit = 2131230829;
			
			// aapt resource value: 0x7f08006e
			public const int btnSettingsCancel = 2131230830;
			
			// aapt resource value: 0x7f08006f
			public const int btnSettingsSubmit = 2131230831;
			
			// aapt resource value: 0x7f08007f
			public const int btnStaffingSubmit = 2131230847;
			
			// aapt resource value: 0x7f080070
			public const int btnStaffingTitle = 2131230832;
			
			// aapt resource value: 0x7f080098
			public const int btnWeeklySubmit = 2131230872;
			
			// aapt resource value: 0x7f080036
			public const int chkAvailFriday = 2131230774;
			
			// aapt resource value: 0x7f080026
			public const int chkAvailMonday = 2131230758;
			
			// aapt resource value: 0x7f08003a
			public const int chkAvailSaturday = 2131230778;
			
			// aapt resource value: 0x7f080022
			public const int chkAvailSunday = 2131230754;
			
			// aapt resource value: 0x7f080032
			public const int chkAvailThursday = 2131230770;
			
			// aapt resource value: 0x7f08002a
			public const int chkAvailTuesday = 2131230762;
			
			// aapt resource value: 0x7f08002e
			public const int chkAvailWednesday = 2131230766;
			
			// aapt resource value: 0x7f080093
			public const int chkFriday = 2131230867;
			
			// aapt resource value: 0x7f08001d
			public const int chkFullTime = 2131230749;
			
			// aapt resource value: 0x7f080087
			public const int chkMonday = 2131230855;
			
			// aapt resource value: 0x7f080037
			public const int chkOpenAvailFriday = 2131230775;
			
			// aapt resource value: 0x7f080027
			public const int chkOpenAvailMonday = 2131230759;
			
			// aapt resource value: 0x7f08003b
			public const int chkOpenAvailSaturday = 2131230779;
			
			// aapt resource value: 0x7f080023
			public const int chkOpenAvailSunday = 2131230755;
			
			// aapt resource value: 0x7f080033
			public const int chkOpenAvailThursday = 2131230771;
			
			// aapt resource value: 0x7f08002b
			public const int chkOpenAvailTuesday = 2131230763;
			
			// aapt resource value: 0x7f08002f
			public const int chkOpenAvailWednesday = 2131230767;
			
			// aapt resource value: 0x7f08001e
			public const int chkOvertime = 2131230750;
			
			// aapt resource value: 0x7f080096
			public const int chkSaturday = 2131230870;
			
			// aapt resource value: 0x7f080083
			public const int chkSunday = 2131230851;
			
			// aapt resource value: 0x7f080090
			public const int chkThursday = 2131230864;
			
			// aapt resource value: 0x7f08008a
			public const int chkTuesday = 2131230858;
			
			// aapt resource value: 0x7f08008d
			public const int chkWednesday = 2131230861;
			
			// aapt resource value: 0x7f08004f
			public const int chooseWeekListView = 2131230799;
			
			// aapt resource value: 0x7f080013
			public const int editInputSFriClose = 2131230739;
			
			// aapt resource value: 0x7f080012
			public const int editInputSFriOpen = 2131230738;
			
			// aapt resource value: 0x7f08000b
			public const int editInputSMonClose = 2131230731;
			
			// aapt resource value: 0x7f08000a
			public const int editInputSMonOpen = 2131230730;
			
			// aapt resource value: 0x7f080015
			public const int editInputSSatClose = 2131230741;
			
			// aapt resource value: 0x7f080014
			public const int editInputSSatOpen = 2131230740;
			
			// aapt resource value: 0x7f080008
			public const int editInputSSunClose = 2131230728;
			
			// aapt resource value: 0x7f080009
			public const int editInputSSunOpen = 2131230729;
			
			// aapt resource value: 0x7f080011
			public const int editInputSThuClose = 2131230737;
			
			// aapt resource value: 0x7f080010
			public const int editInputSThuOpen = 2131230736;
			
			// aapt resource value: 0x7f08000d
			public const int editInputSTueClose = 2131230733;
			
			// aapt resource value: 0x7f08000c
			public const int editInputSTueOpen = 2131230732;
			
			// aapt resource value: 0x7f08000f
			public const int editInputSWedClose = 2131230735;
			
			// aapt resource value: 0x7f08000e
			public const int editInputSWedOpen = 2131230734;
			
			// aapt resource value: 0x7f080049
			public const int empMgmtBtn = 2131230793;
			
			// aapt resource value: 0x7f08001a
			public const int empPageFirstName = 2131230746;
			
			// aapt resource value: 0x7f08001c
			public const int empPageID = 2131230748;
			
			// aapt resource value: 0x7f080019
			public const int empPageLastName = 2131230745;
			
			// aapt resource value: 0x7f08001b
			public const int empPagePosition = 2131230747;
			
			// aapt resource value: 0x7f080048
			public const int historyBtn = 2131230792;
			
			// aapt resource value: 0x7f080059
			public const int historyListView = 2131230809;
			
			// aapt resource value: 0x7f080045
			public const int homeRecentWeeks = 2131230789;
			
			// aapt resource value: 0x7f080038
			public const int inputAvailFriClose = 2131230776;
			
			// aapt resource value: 0x7f080035
			public const int inputAvailFriOpen = 2131230773;
			
			// aapt resource value: 0x7f080028
			public const int inputAvailMonClose = 2131230760;
			
			// aapt resource value: 0x7f080025
			public const int inputAvailMonOpen = 2131230757;
			
			// aapt resource value: 0x7f08003c
			public const int inputAvailSatClose = 2131230780;
			
			// aapt resource value: 0x7f080039
			public const int inputAvailSatOpen = 2131230777;
			
			// aapt resource value: 0x7f080024
			public const int inputAvailSunClose = 2131230756;
			
			// aapt resource value: 0x7f080021
			public const int inputAvailSunOpen = 2131230753;
			
			// aapt resource value: 0x7f080034
			public const int inputAvailThuClose = 2131230772;
			
			// aapt resource value: 0x7f080031
			public const int inputAvailThuOpen = 2131230769;
			
			// aapt resource value: 0x7f08002c
			public const int inputAvailTueClose = 2131230764;
			
			// aapt resource value: 0x7f080029
			public const int inputAvailTueOpen = 2131230761;
			
			// aapt resource value: 0x7f080030
			public const int inputAvailWedClose = 2131230768;
			
			// aapt resource value: 0x7f08002d
			public const int inputAvailWedOpen = 2131230765;
			
			// aapt resource value: 0x7f080065
			public const int inputDefaultShift = 2131230821;
			
			// aapt resource value: 0x7f080094
			public const int inputFriClose = 2131230868;
			
			// aapt resource value: 0x7f080092
			public const int inputFriOpen = 2131230866;
			
			// aapt resource value: 0x7f08006c
			public const int inputFullTime = 2131230828;
			
			// aapt resource value: 0x7f080067
			public const int inputMaxShift = 2131230823;
			
			// aapt resource value: 0x7f080066
			public const int inputMinShift = 2131230822;
			
			// aapt resource value: 0x7f080088
			public const int inputMonClose = 2131230856;
			
			// aapt resource value: 0x7f080086
			public const int inputMonOpen = 2131230854;
			
			// aapt resource value: 0x7f08006a
			public const int inputPartTime = 2131230826;
			
			// aapt resource value: 0x7f080053
			public const int inputPosFrag = 2131230803;
			
			// aapt resource value: 0x7f08007c
			public const int inputSFriClose = 2131230844;
			
			// aapt resource value: 0x7f08007b
			public const int inputSFriOpen = 2131230843;
			
			// aapt resource value: 0x7f080074
			public const int inputSMonClose = 2131230836;
			
			// aapt resource value: 0x7f080073
			public const int inputSMonOpen = 2131230835;
			
			// aapt resource value: 0x7f08007e
			public const int inputSSatClose = 2131230846;
			
			// aapt resource value: 0x7f08007d
			public const int inputSSatOpen = 2131230845;
			
			// aapt resource value: 0x7f080071
			public const int inputSSunClose = 2131230833;
			
			// aapt resource value: 0x7f080072
			public const int inputSSunOpen = 2131230834;
			
			// aapt resource value: 0x7f08007a
			public const int inputSThuClose = 2131230842;
			
			// aapt resource value: 0x7f080079
			public const int inputSThuOpen = 2131230841;
			
			// aapt resource value: 0x7f080076
			public const int inputSTueClose = 2131230838;
			
			// aapt resource value: 0x7f080075
			public const int inputSTueOpen = 2131230837;
			
			// aapt resource value: 0x7f080078
			public const int inputSWedClose = 2131230840;
			
			// aapt resource value: 0x7f080077
			public const int inputSWedOpen = 2131230839;
			
			// aapt resource value: 0x7f080097
			public const int inputSatClose = 2131230871;
			
			// aapt resource value: 0x7f080095
			public const int inputSatOpen = 2131230869;
			
			// aapt resource value: 0x7f080020
			public const int inputShiftPref = 2131230752;
			
			// aapt resource value: 0x7f080068
			public const int inputSkillCap = 2131230824;
			
			// aapt resource value: 0x7f08001f
			public const int inputSkillLevel = 2131230751;
			
			// aapt resource value: 0x7f080084
			public const int inputSunClose = 2131230852;
			
			// aapt resource value: 0x7f080085
			public const int inputSunOpen = 2131230853;
			
			// aapt resource value: 0x7f080091
			public const int inputThuClose = 2131230865;
			
			// aapt resource value: 0x7f08008f
			public const int inputThuOpen = 2131230863;
			
			// aapt resource value: 0x7f08008b
			public const int inputTueClose = 2131230859;
			
			// aapt resource value: 0x7f080089
			public const int inputTueOpen = 2131230857;
			
			// aapt resource value: 0x7f08008e
			public const int inputWedClose = 2131230862;
			
			// aapt resource value: 0x7f08008c
			public const int inputWedOpen = 2131230860;
			
			// aapt resource value: 0x7f08004d
			public const int myListView = 2131230797;
			
			// aapt resource value: 0x7f080046
			public const int newWeekBtn = 2131230790;
			
			// aapt resource value: 0x7f080002
			public const int none = 2131230722;
			
			// aapt resource value: 0x7f080050
			public const int pop_button1 = 2131230800;
			
			// aapt resource value: 0x7f080051
			public const int pop_button2 = 2131230801;
			
			// aapt resource value: 0x7f080056
			public const int posListView = 2131230806;
			
			// aapt resource value: 0x7f080003
			public const int privacyButton = 2131230723;
			
			// aapt resource value: 0x7f080047
			public const int quickWeekBtn = 2131230791;
			
			// aapt resource value: 0x7f080063
			public const int scheduleListView = 2131230819;
			
			// aapt resource value: 0x7f08004b
			public const int settingsBtn = 2131230795;
			
			// aapt resource value: 0x7f080080
			public const int testing_button1 = 2131230848;
			
			// aapt resource value: 0x7f080081
			public const int testing_button2 = 2131230849;
			
			// aapt resource value: 0x7f080064
			public const int textDefaultShift = 2131230820;
			
			// aapt resource value: 0x7f08006b
			public const int textHourTarget = 2131230827;
			
			// aapt resource value: 0x7f080069
			public const int textSkillCap = 2131230825;
			
			// aapt resource value: 0x7f080082
			public const int toolbar = 2131230850;
			
			// aapt resource value: 0x7f08004c
			public const int txtCreateAccount = 2131230796;
			
			// aapt resource value: 0x7f080043
			public const int txtEID = 2131230787;
			
			// aapt resource value: 0x7f080041
			public const int txtFirst = 2131230785;
			
			// aapt resource value: 0x7f080061
			public const int txtFri = 2131230817;
			
			// aapt resource value: 0x7f080040
			public const int txtLast = 2131230784;
			
			// aapt resource value: 0x7f08005d
			public const int txtMon = 2131230813;
			
			// aapt resource value: 0x7f080044
			public const int txtPartFullTime = 2131230788;
			
			// aapt resource value: 0x7f080052
			public const int txtPosFrag = 2131230802;
			
			// aapt resource value: 0x7f080042
			public const int txtPosition = 2131230786;
			
			// aapt resource value: 0x7f080062
			public const int txtSat = 2131230818;
			
			// aapt resource value: 0x7f08005a
			public const int txtScheduleName = 2131230810;
			
			// aapt resource value: 0x7f08005b
			public const int txtSchedulePosition = 2131230811;
			
			// aapt resource value: 0x7f08005c
			public const int txtSun = 2131230812;
			
			// aapt resource value: 0x7f080060
			public const int txtThu = 2131230816;
			
			// aapt resource value: 0x7f08005e
			public const int txtTue = 2131230814;
			
			// aapt resource value: 0x7f08005f
			public const int txtWed = 2131230815;
			
			// aapt resource value: 0x7f080018
			public const int weeklyConfigLayout = 2131230744;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f060000
			public const int google_play_services_version = 2131099648;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int AboutPage = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int AvailChange = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int EditShift = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int EmployeeView = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int EmpMgmtLayout = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int EmpMgmtListView = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int Main = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int NewWeek = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int options_menu = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int PickWeekLayout = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int popup_menu = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int PositionAddFragment = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int PositionManager = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int ScheduleHistory = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int ScheduleListView = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int ScheduleView = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int SettingsView = 2130903056;
			
			// aapt resource value: 0x7f030011
			public const int Splash = 2130903057;
			
			// aapt resource value: 0x7f030012
			public const int StaffingNeeds = 2130903058;
			
			// aapt resource value: 0x7f030013
			public const int testing_menu = 2130903059;
			
			// aapt resource value: 0x7f030014
			public const int ToolBar = 2130903060;
			
			// aapt resource value: 0x7f030015
			public const int WeeklyConfig = 2130903061;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7f040000
			public const int gtm_analytics = 2130968576;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050004
			public const int ApplicationName = 2131034116;
			
			// aapt resource value: 0x7f050003
			public const int Hello = 2131034115;
			
			// aapt resource value: 0x7f050001
			public const int auth_google_play_services_client_facebook_display_name = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int auth_google_play_services_client_google_display_name = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int common_google_play_services_unknown_issue = 2131034114;
			
			// aapt resource value: 0x7f050005
			public const int posPrompt = 2131034117;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070000
			public const int Theme_Splash = 2131165184;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] LoadingImageView = new int[] {
					2130771968,
					2130771969,
					2130771970};
			
			// aapt resource value: 2
			public const int LoadingImageView_circleCrop = 2;
			
			// aapt resource value: 1
			public const int LoadingImageView_imageAspectRatio = 1;
			
			// aapt resource value: 0
			public const int LoadingImageView_imageAspectRatioAdjust = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
