using System;
using System.Collections.Generic;
/// <summary>
/// This exists to hold massive test vars
/// </summary>

namespace MaydSchedulerApp
{
    public static class TempData
    {
        public static string EmpList = @"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfEmployee xmlns:xsd=""http://www.w3.org/2001/XMLSchema"" xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"">
  <Employee>
  <empLastName>B</empLastName>
  <empFirstName>A</empFirstName>
  <empID>1</empID>
  <position>0</position>
  <fullTime>true</fullTime>
  <shiftPreference>8</shiftPreference>
  <skillLevel>8</skillLevel>
  <active>true</active>
  <overtimeAllowed>false</overtimeAllowed>
  <availability>
  <OpenAvailability>true</OpenAvailability>
  </availability>
  </Employee>
  <Employee>
  <empLastName>C</empLastName>
  <empFirstName>B</empFirstName>
  <empID>2</empID>
  <position>0</position>
  <fullTime>true</fullTime>
  <shiftPreference>8</shiftPreference>
  <skillLevel>4</skillLevel>
  <active>true</active>
  <overtimeAllowed>false</overtimeAllowed>
  <availability>
  <OpenAvailability>true</OpenAvailability>
  </availability>
  </Employee>
  <Employee>
  <empLastName>D</empLastName>
  <empFirstName>C</empFirstName>
  <empID>3</empID>
  <position>0</position>
  <fullTime>true</fullTime>
  <shiftPreference>8</shiftPreference>
  <skillLevel>6</skillLevel>
  <active>true</active>
  <overtimeAllowed>false</overtimeAllowed>
  <availability>
  <OpenAvailability>true</OpenAvailability>
  </availability>
  </Employee>
  <Employee>
  <empLastName>E</empLastName>
  <empFirstName>D</empFirstName>
  <empID>4</empID>
  <position>0</position>
  <fullTime>true</fullTime>
  <shiftPreference>8</shiftPreference>
  <skillLevel>10</skillLevel>
  <active>true</active>
  <overtimeAllowed>false</overtimeAllowed>
  <availability>
  <OpenAvailability>true</OpenAvailability>
  </availability>
  </Employee>
  <Employee>
  <empLastName>F</empLastName>
  <empFirstName>E</empFirstName>
  <empID>5</empID>
  <position>0</position>
  <fullTime>true</fullTime>
  <shiftPreference>8</shiftPreference>
  <skillLevel>3</skillLevel>
  <active>true</active>
  <overtimeAllowed>false</overtimeAllowed>
  <availability>
  <OpenAvailability>true</OpenAvailability>
  </availability>
  </Employee>
  <Employee>
  <empLastName>G</empLastName>
  <empFirstName>F</empFirstName>
  <empID>6</empID>
  <position>0</position>
  <fullTime>true</fullTime>
  <shiftPreference>8</shiftPreference>
  <skillLevel>6</skillLevel>
  <active>true</active>
  <overtimeAllowed>false</overtimeAllowed>
  <availability>
  <OpenAvailability>true</OpenAvailability>
  </availability>
  </Employee>
  <Employee>
  <empLastName>H</empLastName>
  <empFirstName>G</empFirstName>
  <empID>7</empID>
  <position>0</position>
  <fullTime>true</fullTime>
  <shiftPreference>8</shiftPreference>
  <skillLevel>5</skillLevel>
  <active>true</active>
  <overtimeAllowed>false</overtimeAllowed>
  <availability>
  <OpenAvailability>true</OpenAvailability>
  </availability>
  </Employee>
  <Employee>
  <empLastName>I</empLastName>
  <empFirstName>H</empFirstName>
  <empID>8</empID>
  <position>0</position>
  <fullTime>true</fullTime>
  <shiftPreference>8</shiftPreference>
  <skillLevel>4</skillLevel>
  <active>true</active>
  <overtimeAllowed>false</overtimeAllowed>
  <availability>
  <OpenAvailability>true</OpenAvailability>
  </availability>
  </Employee>
  <Employee>
  <empLastName>J</empLastName>
  <empFirstName>I</empFirstName>
  <empID>9</empID>
  <position>0</position>
  <fullTime>true</fullTime>
  <shiftPreference>8</shiftPreference>
  <skillLevel>7</skillLevel>
  <active>true</active>
  <overtimeAllowed>false</overtimeAllowed>
  <availability>
  <OpenAvailability>true</OpenAvailability>
  </availability>
  </Employee>
  <Employee>
  <empLastName>K</empLastName>
  <empFirstName>J</empFirstName>
  <empID>10</empID>
  <position>0</position>
  <fullTime>true</fullTime>
  <shiftPreference>8</shiftPreference>
  <skillLevel>8</skillLevel>
  <active>true</active>
  <overtimeAllowed>false</overtimeAllowed>
  <availability>
  <OpenAvailability>true</OpenAvailability>
  </availability>
  </Employee>
  <Employee>
  <empLastName>L</empLastName>
  <empFirstName>K</empFirstName>
  <empID>11</empID>
  <position>0</position>
  <fullTime>true</fullTime>
  <shiftPreference>8</shiftPreference>
  <skillLevel>6</skillLevel>
  <active>true</active>
  <overtimeAllowed>false</overtimeAllowed>
  <availability>
  <OpenAvailability>true</OpenAvailability>
  </availability>
  </Employee>
  <Employee>
  <empLastName>M</empLastName>
  <empFirstName>L</empFirstName>
  <empID>12</empID>
  <position>0</position>
  <fullTime>true</fullTime>
  <shiftPreference>8</shiftPreference>
  <skillLevel>2</skillLevel>
  <active>true</active>
  <overtimeAllowed>false</overtimeAllowed>
  <availability>
  <OpenAvailability>true</OpenAvailability>
  </availability>
  </Employee>
  <Employee>
  <empLastName>N</empLastName>
  <empFirstName>M</empFirstName>
  <empID>13</empID>
  <position>0</position>
  <fullTime>true</fullTime>
  <shiftPreference>8</shiftPreference>
  <skillLevel>9</skillLevel>
  <active>true</active>
  <overtimeAllowed>false</overtimeAllowed>
  <availability>
  <OpenAvailability>true</OpenAvailability>
  </availability>
  </Employee>
  <Employee>
  <empLastName>O</empLastName>
  <empFirstName>N</empFirstName>
  <empID>14</empID>
  <position>0</position>
  <fullTime>true</fullTime>
  <shiftPreference>8</shiftPreference>
  <skillLevel>4</skillLevel>
  <active>true</active>
  <overtimeAllowed>false</overtimeAllowed>
  <availability>
  <OpenAvailability>true</OpenAvailability>
  </availability>
  </Employee>
  <Employee>
  <empLastName>P</empLastName>
  <empFirstName>O</empFirstName>
  <empID>15</empID>
  <position>0</position>
  <fullTime>true</fullTime>
  <shiftPreference>8</shiftPreference>
  <skillLevel>9</skillLevel>
  <active>true</active>
  <overtimeAllowed>false</overtimeAllowed>
  <availability>
  <OpenAvailability>true</OpenAvailability>
  </availability>
  </Employee>
  <Employee>
  <empLastName>Q</empLastName>
  <empFirstName>P</empFirstName>
  <empID>16</empID>
  <position>0</position>
  <fullTime>true</fullTime>
  <shiftPreference>8</shiftPreference>
  <skillLevel>6</skillLevel>
  <active>true</active>
  <overtimeAllowed>false</overtimeAllowed>
  <availability>
  <OpenAvailability>true</OpenAvailability>
  </availability>
  </Employee>
  <Employee>
  <empLastName>R</empLastName>
  <empFirstName>Q</empFirstName>
  <empID>17</empID>
  <position>0</position>
  <fullTime>true</fullTime>
  <shiftPreference>8</shiftPreference>
  <skillLevel>7</skillLevel>
  <active>true</active>
  <overtimeAllowed>false</overtimeAllowed>
  <availability>
  <OpenAvailability>true</OpenAvailability>
  </availability>
  </Employee>
  <Employee>
  <empLastName>S</empLastName>
  <empFirstName>R</empFirstName>
  <empID>18</empID>
  <position>0</position>
  <fullTime>true</fullTime>
  <shiftPreference>8</shiftPreference>
  <skillLevel>3</skillLevel>
  <active>true</active>
  <overtimeAllowed>false</overtimeAllowed>
  <availability>
  <OpenAvailability>true</OpenAvailability>
  </availability>
  </Employee>
  <Employee>
  <empLastName>T</empLastName>
  <empFirstName>S</empFirstName>
  <empID>19</empID>
  <position>0</position>
  <fullTime>true</fullTime>
  <shiftPreference>8</shiftPreference>
  <skillLevel>8</skillLevel>
  <active>true</active>
  <overtimeAllowed>false</overtimeAllowed>
  <availability>
  <OpenAvailability>true</OpenAvailability>
  </availability>
  </Employee>
  <Employee>
  <empLastName>U</empLastName>
  <empFirstName>T</empFirstName>
  <empID>20</empID>
  <position>0</position>
  <fullTime>true</fullTime>
  <shiftPreference>8</shiftPreference>
  <skillLevel>8</skillLevel>
  <active>true</active>
  <overtimeAllowed>false</overtimeAllowed>
  <availability>
  <OpenAvailability>true</OpenAvailability>
  </availability>
  </Employee>
  <Employee>
  <empLastName>V</empLastName>
  <empFirstName>U</empFirstName>
  <empID>21</empID>
  <position>1</position>
  <fullTime>true</fullTime>
  <shiftPreference>8</shiftPreference>
  <skillLevel>10</skillLevel>
  <active>true</active>
  <overtimeAllowed>false</overtimeAllowed>
  <availability>
  <OpenAvailability>true</OpenAvailability>
  </availability>
  </Employee>
  <Employee>
  <empLastName>W</empLastName>
  <empFirstName>V</empFirstName>
  <empID>22</empID>
  <position>1</position>
  <fullTime>true</fullTime>
  <shiftPreference>8</shiftPreference>
  <skillLevel>10</skillLevel>
  <active>true</active>
  <overtimeAllowed>false</overtimeAllowed>
  <availability>
  <OpenAvailability>true</OpenAvailability>
  </availability>
  </Employee>
  <Employee>
  <empLastName>X</empLastName>
  <empFirstName>W</empFirstName>
  <empID>23</empID>
  <position>1</position>
  <fullTime>true</fullTime>
  <shiftPreference>8</shiftPreference>
  <skillLevel>10</skillLevel>
  <active>true</active>
  <overtimeAllowed>false</overtimeAllowed>
  <availability>
  <OpenAvailability>true</OpenAvailability>
  </availability>
  </Employee>
</ArrayOfEmployee>";
    }
}